### ISSUE TITLE
 have a valid base64 image which I am running through the sanitizer but its being scrubbed.

### ISSUE THREAD

**Issue by vivekscripts** [mganss/HtmlSanitizer#95] opened 2016-11-23 06:06 UTC
Here is the base64 image text
[Base64Image.txt](https://github.com/mganss/HtmlSanitizer/files/608173/Base64Image.txt)

**Comment by tiesont** [comment] 2016-11-23 06:45
Did you read #66?

**Comment by vivekscripts** [comment] 2016-11-23 07:22
Here is anothernone which doesn't work with AllowDataAttribute = true & AllowedSchemes has "data" in it.
it's pretty weird that some images work and some doesn't (of course the one's have malicious code should be sanitized but these are my screen captures and some works with these settings and some doesn't)

is there any other way that all <img src=data:image/png;base64,........./> can be configured to be allowed?

[Base64Image-2.txt](https://github.com/mganss/HtmlSanitizer/files/608272/Base64Image-2.txt)

**Comment by mganss** [comment] 2016-11-23 12:45
The first file contains a non-base64 character (`…`) at position 5000. The second is due to #66, where there's also a workaround.

**Comment by mganss** [comment] 2016-12-14 12:19
Duplicate of #66

**Closed by mganss** 2016-12-14 12:19 UTC
