### ISSUE TITLE
How do we handle emails in angle brackets

### ISSUE THREAD

**Issue by CodePala** [mganss/HtmlSanitizer#179] opened 2019-07-24 12:31 UTC
Team, 

When we are using htmlsanitizer in an example like below, everything after left angle bracket is being removed. But we need to keep the emails in the text. How do we handle these scenarios? 

Example :    testuser <testuser@xyz.com> custom notes to user 

When we use sanitizer, everything is being cleaned up in the above example except first word "testuser".

**Comment by mganss** [comment] 2019-07-24 13:34
Duplicate of #126. See https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing for a solution.

**Closed by mganss** 2019-07-24 13:34 UTC
