### ISSUE TITLE
Text removed after sanitizing a self closed tag that is not allowed (iframe)

### ISSUE THREAD

**Issue by jonatanverschaeren** [mganss/HtmlSanitizer#135] opened 2018-03-01 15:44 UTC
Hi,

When I enter the following input in the sanitizer demo, the text after the iframe tag is removed when sanitizing the input (the tag itself is also removed which is good):
```html
This text stays <iframe src="http://google.be" /> This text is removed but should stay
```

If I close the iframe tag correctly, then the text after the tag is not removed:
```html
This text stays <iframe src="http://google.be"></iframe> This text is NOT removed
```

I also wrote a test for this in the HtmlSanitizer solution and have the same results.
Is this a bug or is this intended behaviour?

Kind Regards,

Jonatan

**Comment by mganss** [comment] 2018-03-01 16:19
This is intended behavior because the HTML in the first example is invalid HTML and the parser treats the self-closing tag as a start tag. The [HTML validator](https://html5.validator.nu/) says:
```
Error: Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
```

**Closed** 2018-08-01 14:15 UTC

**Comment by sanjogs** [comment] 2022-01-14 16:01
@mganss Any workaround for this, We have similar html coming from external environment which is not under our control, and basically all the text after custom tag including the tag is getting wiped out. Is there a way to correct these self closing tags first?

**Comment by mganss** [comment] 2022-01-14 16:08
@sanjogs Correcting invalid HTML is outside of the scope of HtmlSanitizer. You might want to try an approach similar to the one presented here: https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing
