### ISSUE TITLE
Russian text support inside html(for example in the test SanitizeEscapeAttrTest)

### ISSUE THREAD

**Issue by igor-shubin** [mganss/HtmlSanitizer#30] opened 2015-06-05 15:26 UTC
Thank you for your answer https://github.com/mganss/HtmlSanitizer/issues/29. But it breaks the protection:

```
    var sanitizer = new HtmlSanitizer();
    var html = @"<div title=""&lt;foo&gt;"">Тест</div>";
    var outputFormatter = new CsQuery.Output.FormatDefault(DomRenderingOptions.RemoveComments | DomRenderingOptions.QuoteAllAttributes, HtmlEncoders.Minimum);
    var actual = sanitizer.Sanitize(html, "", outputFormatter);
    Assert.That(actual, Is.EqualTo(@"<div title=""&lt;foo&gt;"">Тест</div>").IgnoreCase);
```

```
  Expected string length 35 but was 29. Strings differ at index 12.
  Expected: "<div title="&lt;foo&gt;">Тест</div>", ignoring case
  But was:  "<div title="<foo>">Тест</div>"
  -----------------------^
```

**Comment by mganss** [comment] 2015-06-05 15:33
Duplicate of #29

**Closed by mganss** 2015-06-05 15:33 UTC
