### ISSUE TITLE
Option to not unencode my encoded characters

### ISSUE THREAD

**Issue by nosmalldreams** [mganss/HtmlSanitizer#211] opened 2020-03-03 23:50 UTC
I'm noticing that when I run text through HTMLSanitizer that contains encoded special characters they are UNENCODED in the output. (e.g. `&ldquo;` in my source string becomes the actual curly quotation character in the sanitized string, `&amp;` becomes simply &, etc. This is certainly not what I expected, and is an issue for me.

My code is very simple so I don't think I could be calling the sanitizer wrong, but maybe there is some parameter/configuration I'm unaware of? - this is my sanitizer call: 

     var sanitizer = new HtmlSanitizer();
     var sanitized = sanitizer.Sanitize(htmlString);

Thank you for your assistance!

**Comment by mganss** [comment] 2020-03-04 11:47
This is a duplicate of #190. It is not true for `&amp;`, though, neither for `&nbsp;`, `&quot;`, `&lt;`, and `&gt;`. See relevant spec here: https://html.spec.whatwg.org/#escapingString

Why is it an issue for your use case?

**Closed by mganss** 2020-03-04 11:47 UTC
