### ISSUE TITLE
Sanitizer 5.x remove fonts

### ISSUE THREAD

**Issue by lukapor** [mganss/HtmlSanitizer#224] opened 2020-05-22 06:20 UTC
Hi I try to upgraded html sanitiner library from version 4.x to 5.x

I have some issues with version 5 which clean to much :)

I call just simple sanitize (code below)

[htmls.zip](https://github.com/mganss/HtmlSanitizer/files/4666386/htmls.zip)

var sanitizer = new HtmlSanitizer();
sanitizer.Sanitize(html);

Version 5 cleans all fonts defined as font: ..

I attached html.html as original source, and html as result after cleaning with versions 4.x and 5.x

**Comment by mganss** [comment] 2020-05-22 15:21
Thanks for reporting this. The problem is with the numerical specification of `font-weight` in the `font` shorthand. This seems to be a bug in AngleSharp.Css. I've submitted an issue here: https://github.com/AngleSharp/AngleSharp.Css/issues/56

**Comment by mganss** [comment] 2020-05-25 10:25
This was fixed in https://github.com/AngleSharp/AngleSharp.Css/pull/57 and will be fixed in HtmlSanitizer with the next release of AngleSharp.Css.

**Comment by mganss** [comment] 2020-06-12 10:11
Fixed in 5.0.331.

**Closed by mganss** 2020-06-12 10:11 UTC
